### ISSUE TITLE
How to call the library in MATLAB?

### ISSUE THREAD

**Issue by BoyuLyu** [tatsy/tinymesh#5]
Can I call the library in MATLAB?
It seems that a static library .a file is generated under running CMake in Ubuntu. 
I understand that I might need to write a wrapper for MATLAB, but could you give some suggestions? Thanks!

**Comment by tatsy** [comment]
I am not quite familiar with MATLAB, but if it is possible to convert Eigen::MatrixXd and Eigen::VectorXd to MATLAB’s own representations, I think it could be possible.

One thing I am concerned is that some functions return a general Mesh object. I am not sure that such an object can be received by MATLAB. But if it is possible, the library can be available in MATLAB by writing some wrappers, though I am not plan to do so.

A more easy way to integrate this library with MATLAB is call the shell command from MATLAB and read out the output file from MATLAB.

Thank you for your interest to my library, and hole it helps!

**Comment by BoyuLyu** [comment]
Thanks! I wrote a mex as a wrapper function, and it worked by linking the library tinymesh.a and the header tinymesh.h.
