### ISSUE TITLE
Unable to pip install the package

### ISSUE THREAD

**Issue by caoandong** [tatsy/tinymesh#6]
Hi, thank you for creating this amazing library! I am facing some trouble installing this library as a python module.

To reproduce:
Simply run the installation instruction (on ubuntu):
```
pip install git+https://github.com/tatsy/tinymesh.git
```
And import the library from python:
```
python -c "import tinymesh"
```
This will give the following error:
```
ModuleNotFoundError: No module named 'tinymesh'
```
I made sure that the module is installed under the correct python version, and searching the `site_packages` I am able to find tinymesh with the following files:
```
ls /opt/conda/lib/python3.10/site-packages/tinymesh-0.2.3.dist-info       
INSTALLER  LICENSE  METADATA  RECORD  REQUESTED  WHEEL  direct_url.json
```
However python cannot find the module somehow.

Do you know how to fix this issue? Is there some problem with pybind11?

Thank you!

**Comment by tatsy** [comment]
Hi, can you show me your environment, mean OS, Python version, Python installation method (system, conda, vritualenv, etc.)?

**Comment by caoandong** [comment]
Hi, I simply run the installation on a clean docker image:

```
pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel
```

The python version is `3.10.13`, and the package is installed just by running `pip`, I didn't use `conda` or `virtualenv`.

I also tried running `poetry` and it doesn't work either.

If possible, would you provide a Dockerfile to install tinymesh? Thank you so much!

**Comment by tatsy** [comment]
Hi, I am not pretty sure about the reason, but I have update the build script a bit. I'd appreciate it if you would try it again.
If it fails, I also prepared the wheels and believe it must work on later ones of Ubuntu (probably 20.04 or later).
https://github.com/tatsy/tinymesh/releases/tag/v0.2.4

**Comment by caoandong** [comment]
Thank you so much for your help! I'll let you know if the build is able to run; if so, I'll publish a docker image on docker hub.
